export const PUBLISHABLE_KEY = 'pk_test_XXXXXXXXXXXXXXXXXXXXXXXX';

export const SHOULD_ERROR_KEY = 'SHOULD_ERROR_KEY';

export const TOKEN_ERROR_KEY = 'TOKEN_ERROR_KEY';

export const INCOMPLETE_CARD_KEY = 'INCOMPLETE_CARD_KEY';

export const CLIENT_SECRET = 'CLIENT_SECRET';

export const CARD_CONFIRM_ERROR_SECRET = 'CARD_CONFIRM_ERROR_SECRET';
